apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskflow-api
  namespace: taskflow-dev
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: taskflow
  namespaceSelector:
    matchNames:
      - taskflow-dev
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
