apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskflow.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.config.environment | quote }}
  ASPNETCORE_URLS: "http://+:{{ .Values.service.port }}"
  MongoDb__DatabaseName: {{ .Values.mongodb.databaseName | quote }}
  Jwt__Issuer: {{ .Values.config.jwtIssuer | quote }}
  Jwt__Audience: {{ .Values.config.jwtAudience | quote }}
  Jwt__ExpiryMinutes: {{ .Values.config.jwtExpiryMinutes | quote }}
  Otel__Endpoint: {{ .Values.otel.endpoint | quote }}
