apiVersion: v1
kind: Secret
metadata:
  name: {{ include "taskflow.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "taskflow.labels" . | nindent 4 }}
type: Opaque
data:
  MongoDb__ConnectionString: {{ .Values.mongodb.connectionString | b64enc | quote }}
  Jwt__Key: {{ .Values.config.jwtKey | b64enc | quote }}
